In [61]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [62]:
# Kiểm tra phiên bản numpy hiện tại sau khi restart
import numpy as np
print(np.__version__)  # Phải là 1.26.4


1.26.4


In [63]:
# !git clone https://github.com/cszn/BSRGAN.git
# %cd BSRGAN
# !pip install -r requirements.txt


In [64]:
!pip show ultralytics

Name: ultralytics
Version: 8.3.169
Summary: Ultralytics YOLO 🚀 for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.
Home-page: https://ultralytics.com
Author: 
Author-email: Glenn Jocher <glenn.jocher@ultralytics.com>, Jing Qiu <jing.qiu@ultralytics.com>
License: AGPL-3.0
Location: /usr/local/lib/python3.11/dist-packages
Requires: matplotlib, numpy, opencv-python, pandas, pillow, psutil, py-cpuinfo, pyyaml, requests, scipy, torch, torchvision, tqdm, ultralytics-thop
Required-by: 


In [65]:
# # Cài đặt PyTorch phù hợp với CUDA 11.8 trên Colab
# !pip install torch==2.1.0 torchvision==0.16.0 -f https://download.pytorch.org/whl/cu118/torch_stable.html

# # Cài đúng phiên bản numpy để tránh lỗi tương thích
# !pip install numpy==1.26.4

# # Cài đặt Ultralytics YOLO và supervision (dựa trên torch đã cài)
# !pip install ultralytics supervision



In [66]:
!pip install ultralytics==8.3.169 --no-deps

In [67]:
import numpy as np
print(np.__version__)  # Phải ra 1.26.4


1.26.4


In [68]:
# from ultralytics import YOLO
# import supervision as sv
# import cv2
# import os
# import torch

# # Cấu hình
# image_dir = "images_to_labels"
# label_dir = "labels"
# os.makedirs(label_dir, exist_ok=True)

# # Load mô hình YOLOv8 đã pre-trained
# model = YOLO("yolov8n.pt")  # hoặc yolov8s.pt, yolov8m.pt,...

# # Tạo annotator
# for image_name in os.listdir(image_dir):
#     if not image_name.lower().endswith(('.png', '.jpg', '.jpeg')):
#         continue

#     image_path = os.path.join(image_dir, image_name)
#     image = cv2.imread(image_path)

#     # Detect
#     results = model(image)[0]
#     h, w = image.shape[:2]

#     # Ghi file nhãn YOLO
#     label_file = os.path.join(label_dir, image_name.rsplit(".", 1)[0] + ".txt")
#     with open(label_file, "w") as f:
#         for r in results.boxes:
#             cls = int(r.cls[0])
#             cx, cy, bw, bh = r.xywh[0].cpu() / torch.tensor([w, h, w, h]) # chuẩn hóa theo ảnh
#             f.write(f"{cls} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}\n")

In [69]:
# !cp -r /content/BSRGAN /content/drive/MyDrive/VideoUpScaling

In [70]:
# !wget https://github.com/cszn/KAIR/releases/download/v1.0/BSRGAN.pth -P model_zoo


In [71]:
import numpy as np
print(np.__version__)  # Kiểm tra đang là 1.26.4 hay không


1.26.4


In [72]:
import sys
sys.path.append('/content/drive/MyDrive')

import os
from PIL import Image
from VideoUpScaling import utils
import torch
import torchvision.transforms as transforms
from VideoUpScaling import BSRGANModule

# Tạo model

In [73]:
# import os

# if not os.path.exists('/content/dataset'):
#     !unzip /content/dataset.zip
# else:
#     print("Dataset already exists, skipping extraction.")

In [74]:
# !cp -r /content/drive/MyDrive/images_to_labels /content/

**Reasoning**:
The user wants to load the BSRGAN model. I will import the necessary libraries, instantiate the model, load the pre-trained weights, and set it to evaluation mode, as per the instructions.



# Task
Enhance all images in the "dataset" folder by a factor of 4 using the BSRGAN model from "/content/drive/MyDrive/VideoUpScaling/BSRGANModule.py".  Also, scale the bounding box coordinates in the corresponding label files by the same factor. Save the enhanced images and updated labels to a new "dataset_enhanced" folder.

## Create output directories

### Subtask:
Create the output directories 'dataset_enhanced/images' and 'dataset_enhanced/labels' to store the upscaled images and their corresponding labels.


**Reasoning**:
I will create the output directories as requested by the user, using `os.makedirs` with `exist_ok=True` to prevent errors if the directories already exist.



In [75]:
import os

# Create output directories
output_image_dir = '/content/drive/MyDrive/VideoUpScaling/dataset_enhanced/images'
output_label_dir = '/content/drive/MyDrive/VideoUpScaling/dataset_enhanced/labels'

os.makedirs(output_image_dir, exist_ok=True)
os.makedirs(output_label_dir, exist_ok=True)

print(f"Created directory: {output_image_dir}")
print(f"Created directory: {output_label_dir}")

Created directory: /content/drive/MyDrive/VideoUpScaling/dataset_enhanced/images
Created directory: /content/drive/MyDrive/VideoUpScaling/dataset_enhanced/labels


In [76]:
%cd /content/drive/MyDrive/VideoUpScaling
!pwd

/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling
/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling


In [77]:
train=True

In [78]:
if train:
  import sys
  sys.path.append('/content/drive/MyDrive')



  from VideoUpScaling.utils import utils_logger
  from VideoUpScaling.utils import utils_image as util
  import logging
  import os.path
  # Define paths
  input_image_dir = '/content/drive/MyDrive/VideoUpScaling/dataset/images/train'
  input_label_dir = '/content/drive/MyDrive/VideoUpScaling/dataset/labels'
  output_image_dir = '/content/drive/MyDrive/VideoUpScaling/dataset_enhanced/images/train'
  output_label_dir = '/content/drive/MyDrive/VideoUpScaling/dataset_enhanced/labels/train'


  # # Initialize the BSRGAN model
  # model = BSRGAN_module(sf=4)  # sf=4 for 4x upscaling
  # model.load_netG(model_path)
  # model.netG.to('cuda' if torch.cuda.is_available() else 'cpu')
  # model.netG.eval()
  model = BSRGANModule.BSRGAN(model_names=["BSRGAN"],scale_factor=4)
  # Process each image and its corresponding label file
  for image_name in os.listdir(input_image_dir):
      if not image_name.lower().endswith(('.png', '.jpg', '.jpeg')):
          continue

      image_path = os.path.join(input_image_dir, image_name)
      print(f"Processing image: {image_path}")  # Print the path of the image
      label_path = os.path.join(input_label_dir, os.path.splitext(image_name)[0] + '.txt')

      # # Enhance the image
      # img_L = util.imread_uint(image_path, n_channels=3)
      # img_L = util.uint2tensor4(img_L)
      # img_L = img_L.to('cuda' if torch.cuda.is_available() else 'cpu')

      # with torch.no_grad():
      #     img_E = model.netG(img_L)

      # img_E = util.tensor2uint(img_E)
      # output_image_path = os.path.join(output_image_dir, image_name)
      # util.imsave(img_E, output_image_path)

      save_results=model.Enhance(input=image_path)
      util.imsave(save_results, os.path.join(output_image_dir,image_name+'.png'))


      # # Scale and save the new labels
      # if os.path.exists(input_label_dir):
      #     with open(input_label_dir, 'r') as f_in, open(os.path.join(output_label_dir, os.path.splitext(image_name)[0] + '.txt'), 'w') as f_out:
      #         for line in f_in:
      #             parts = line.strip().split()
      #             cls = int(parts[0])
      #             x_center, y_center, width, height = map(float, parts[1:])

      #             # Bounding box coordinates are relative to image size, so no change is needed.
      #             f_out.write(f"{cls} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}\n")


  print("Image enhancement and label processing complete.")

Processing image: /content/drive/MyDrive/VideoUpScaling/dataset/images/train/frame_00285_tile_1_1.png
LogHandlers exist!
[3, 3, 64, 23, 32, 4]
ảnh đâu ra:  [[[139 101 110]
  [130 104 100]
  [132 109 110]
  ...
  [117 114 115]
  [117 115 116]
  [113 115 113]]

 [[142 112 118]
  [147 115 117]
  [143 111 110]
  ...
  [119 115 115]
  [115 115 116]
  [114 116 112]]

 [[137 111 115]
  [145 111 115]
  [137 109 110]
  ...
  [117 115 115]
  [117 116 116]
  [115 114 116]]

 ...

 [[137 122 125]
  [137 126 131]
  [140 129 133]
  ...
  [183 168 170]
  [186 170 170]
  [186 165 171]]

 [[147 122 127]
  [141 130 134]
  [145 130 135]
  ...
  [184 165 170]
  [187 167 167]
  [177 165 163]]

 [[138 136 133]
  [133 123 133]
  [146 130 135]
  ...
  [188 166 165]
  [187 166 163]
  [179 171 168]]]
Đường dẫn của ảnh:  /content/drive/MyDrive/VideoUpScaling/dataset_enhanced/images/frame_00285_tile_1_1.png.png
Processing image: /content/drive/MyDrive/VideoUpScaling/dataset/images/train/frame_00057_tile_1_1.png
L

KeyboardInterrupt: 

In [79]:
%cd /content/dataset_enhanced/images
%ls

[Errno 2] No such file or directory: '/content/dataset_enhanced/images'
/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling
10.72.216.20_.mp4                   mergingfile.py
BSRGAN/                             models/
BSRGANModule.py                     model_zoo/
checkdata.py                        __pycache__/
DataPreprocessing.py                reconstructed_00855.png
dataset/                            requirements.txt
dataset_enhanced/                   runs/
data.yaml                           taotxttudong.py
InferenceTest/                      test.png
main_download_pretrained_models.py  testsets/
main_test_bsrgan.py                 TilesDivision.py
maketraintxt.py                     utils/


In [80]:
# !zip -r /content/dataset_enhanced.zip /content/dataset_enhanced

In [81]:
# from google.colab import files
# files.download('/content/dataset_enhanced.zip')

In [82]:
# !cp /content/dataset/val.txt /content/dataset_enhanced

In [83]:
import os
if train:
    image_dir = '/content/drive/MyDrive/VideoUpScaling/dataset_enhanced/images'

    for filename in os.listdir(image_dir):
        if filename.endswith('.png.png'):
            new_filename = filename[:-4]
            os.rename(os.path.join(image_dir, filename), os.path.join(image_dir, new_filename))

    print("Filenames have been corrected.")

Filenames have been corrected.


In [84]:
# import os
# import shutil
# if train:
#     source_dir = '/content/drive/MyDrive/VideoUpScaling/dataset/images/train'
#     destination_dir = '/content/drive/MyDrive/VideoUpScaling/dataset_enhanced/labels'

#     # Create destination directory if it doesn't exist
#     os.makedirs(destination_dir, exist_ok=True)

#     # Copy all .txt files
#     for filename in os.listdir(source_dir):
#         if filename.endswith('.txt'):
#             shutil.copy(os.path.join(source_dir, filename), destination_dir)

#     print("All .txt files have been copied.")

All .txt files have been copied.


In [92]:
# if train:
#     import os

#     # Modify train.txt
#     with open('/content/drive/MyDrive/VideoUpScaling/dataset_enhanced/train.txt', 'r') as f_in:
#         lines = f_in.readlines()

#     with open('/content/drive/MyDrive/VideoUpScaling/dataset_enhanced/train.txt', 'w') as f_out:
#         for line in lines:
#             f_out.write(line.replace('train/', ''))

#     print("train.txt has been modified.")

train.txt has been modified.


In [ ]:
if train:
    import os

    train_txt_path = '/content/drive/MyDrive/VideoUpScaling/dataset_enhanced/train.txt'
    image_dir_prefix = '/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/train/'

    # Read original lines (could be full paths or just filenames)
    with open(train_txt_path, 'r') as f:
        lines = f.readlines()

    # Overwrite with correct full path format
    with open(train_txt_path, 'w') as f:
        for line in lines:
            filename = os.path.basename(line.strip())  # Extract filename only
            if filename:
                full_path = os.path.join(image_dir_prefix, filename)
                f.write(full_path + '\n')

    print(f"✅ train.txt đã được cập nhật đường dẫn đầy đủ.")


In [87]:
# import os
# import shutil

# source_dir = '/content/dataset_enhanced/images'
# destination_dir = '/content/dataset_enhanced/images_moved'

# # Create destination directory if it doesn't exist
# os.makedirs(destination_dir, exist_ok=True)

# # Get a sorted list of files
# files = sorted(os.listdir(source_dir))

# # Find the starting index
# try:
#     start_index = files.index('frame_00285_tile_2_0.png')
# except ValueError:
#     print("The specified file was not found in the directory.")
#     start_index = -1

# # Move the files
# if start_index != -1:
#     for i in range(start_index, len(files)):
#         shutil.move(os.path.join(source_dir, files[i]), destination_dir)
#     print(f"Moved {len(files) - start_index} files to {destination_dir}")

In [88]:
# !cp -r /content/dataset_enhanced /content/drive/MyDrive/VideoUpScaling
# !cp -r /content/dataset /content/drive/MyDrive/VideoUpScaling

In [89]:
%cd /content/drive/MyDrive/VideoUpScaling/dataset_enhanced

/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced


In [90]:
if train:
    import os

    train_txt_path = '/content/drive/MyDrive/VideoUpScaling/dataset_enhanced/train.txt'
    image_dir_prefix = '/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/'

    # Read the original train.txt
    with open(train_txt_path, 'r') as f:
        lines = f.readlines()

    # Write the modified paths to train.txt
    with open(train_txt_path, 'w') as f:
        for line in lines:
            line = line.strip()
            if line:  # Ensure the line is not empty
                # Extract the filename after 'train.txt/images/'
                parts = line.split('train.txt/images/')
                if len(parts) > 1:
                    image_filename = parts[-1]
                    f.write(f'{image_dir_prefix}{image_filename}\n')
                else:
                    # If the expected pattern is not found, assume the line is already just the filename
                    image_filename = line
                    f.write(f'{image_dir_prefix}{image_filename}\n')

    print(f"Modified {train_txt_path} with updated image paths.")

Modified /content/drive/MyDrive/VideoUpScaling/dataset_enhanced/train.txt with updated image paths.


In [94]:
if train:
  from ultralytics import YOLO

  # Load model
  model = YOLO('yolov8n.yaml')  # hoặc yolov8s.yaml, yolov8m.yaml...

  # Train
  model.train(data='data.yaml', epochs=50, imgsz=640, batch=16)

New https://pypi.org/project/ultralytics/8.3.170 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.169 🚀 Python-3.11.13 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=train8, nbs=64, nms=False, opset=None, optimize=False, optimizer=aut

train: Scanning /content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/labels/train... 51 images, 22 backgrounds, 255 corrupt: 100%|██████████| 306/306 [00:25<00:00, 11.94it/s]

train: /content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/train/frame_00285_tile_2_0.png: ignoring corrupt image/label: [Errno 2] No such file or directory: '/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/train/frame_00285_tile_2_0.png'
train: /content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/train/frame_00285_tile_2_1.png: ignoring corrupt image/label: [Errno 2] No such file or directory: '/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/train/frame_00285_tile_2_1.png'
train: /content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/train/frame_00285_tile_2_2.png: ignoring corrupt image/label: [Errno 2] No such file or directory: '/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0

train: New cache created: /content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
WARNING ⚠️ val: Image speed checks: failed to access files


val: Scanning /content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/labels/train.cache... 51 images, 22 backgrounds, 255 corrupt: 100%|██████████| 306/306 [00:00<?, ?it/s]

train: /content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/train/frame_00285_tile_2_0.png: ignoring corrupt image/label: [Errno 2] No such file or directory: '/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/train/frame_00285_tile_2_0.png'
train: /content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/train/frame_00285_tile_2_1.png: ignoring corrupt image/label: [Errno 2] No such file or directory: '/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/train/frame_00285_tile_2_1.png'
train: /content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/images/train/frame_00285_tile_2_2.png: ignoring corrupt image/label: [Errno 2] No such file or directory: '/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0

Plotting labels to runs/detect/train8/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.001111, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs/detect/train8
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/50      2.04G      5.686      9.528      4.274         33        640: 100%|██████████| 4/4 [00:03<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.24s/it]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/50      2.05G      5.374      6.257      4.376         17        640: 100%|██████████| 4/4 [00:01<00:00,  2.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  2.16it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/50      2.05G       5.61      7.965      4.303         19        640: 100%|██████████| 4/4 [00:01<00:00,  2.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  4.04it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/50      2.05G      3.498      10.19      3.263          0        640: 100%|██████████| 4/4 [00:01<00:00,  2.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  3.66it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/50      2.05G      4.837      6.766      4.238          9        640: 100%|██████████| 4/4 [00:01<00:00,  3.31it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.98it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/50      2.05G      4.963      5.809      4.219         24        640: 100%|██████████| 4/4 [00:01<00:00,  3.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.70it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/50      2.05G       3.49      10.15      3.155          0        640: 100%|██████████| 4/4 [00:01<00:00,  2.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.34it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/50      2.05G      5.082      6.499      4.138         19        640: 100%|██████████| 4/4 [00:01<00:00,  2.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.75it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/50      2.05G      5.248      7.782      4.131         10        640: 100%|██████████| 4/4 [00:01<00:00,  3.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.81it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/50      2.05G      4.652       5.87      4.125         16        640: 100%|██████████| 4/4 [00:01<00:00,  3.67it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.65it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/50      2.05G      4.808        6.4      4.151          4        640: 100%|██████████| 4/4 [00:01<00:00,  3.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.33it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/50      2.05G      4.518      5.758      4.139         21        640: 100%|██████████| 4/4 [00:01<00:00,  2.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.94it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/50      2.05G      4.486       5.49      4.006          8        640: 100%|██████████| 4/4 [00:01<00:00,  3.38it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.94it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/50      2.06G      4.526      5.461      3.941         20        640: 100%|██████████| 4/4 [00:01<00:00,  3.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  2.18it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/50      2.06G      4.466       4.59      3.897         16        640: 100%|██████████| 4/4 [00:01<00:00,  3.31it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.70it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      16/50      2.06G      4.417      4.516       3.85         20        640: 100%|██████████| 4/4 [00:01<00:00,  2.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.20it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      17/50      2.06G      3.886      4.892      3.808         10        640: 100%|██████████| 4/4 [00:01<00:00,  3.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.58it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      18/50      2.06G      4.139      4.902       3.71         11        640: 100%|██████████| 4/4 [00:01<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.98it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      19/50      2.06G      4.242      4.361      3.753         17        640: 100%|██████████| 4/4 [00:01<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.79it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      20/50      2.06G      4.322      4.156      3.666         17        640: 100%|██████████| 4/4 [00:01<00:00,  2.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.07it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      21/50      2.06G      3.784      4.591      3.584          6        640: 100%|██████████| 4/4 [00:01<00:00,  2.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.65it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      22/50      2.06G      4.184      4.745      3.574         18        640: 100%|██████████| 4/4 [00:01<00:00,  3.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.49it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      23/50      2.06G       4.35      8.776       3.56          6        640: 100%|██████████| 4/4 [00:01<00:00,  3.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.69it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      24/50      2.06G      4.187      10.98      3.422          1        640: 100%|██████████| 4/4 [00:01<00:00,  2.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.17it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      25/50      2.06G        4.1       4.12       3.46         29        640: 100%|██████████| 4/4 [00:01<00:00,  2.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  2.01it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      26/50      2.06G      3.761      4.253      3.478         11        640: 100%|██████████| 4/4 [00:01<00:00,  3.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  2.13it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      27/50      2.06G      3.937      4.446      3.576         18        640: 100%|██████████| 4/4 [00:01<00:00,  2.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.75it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      28/50      2.06G      3.807      6.586      3.343          5        640: 100%|██████████| 4/4 [00:01<00:00,  3.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.46it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      29/50      2.06G      3.661      4.374      3.392         18        640: 100%|██████████| 4/4 [00:01<00:00,  2.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.30it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      30/50      2.06G      3.643       4.14      3.401          8        640: 100%|██████████| 4/4 [00:01<00:00,  3.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.78it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      31/50      2.06G      4.006      4.113      3.323         27        640: 100%|██████████| 4/4 [00:01<00:00,  3.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.79it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      32/50      2.06G      3.706      3.979      3.215          9        640: 100%|██████████| 4/4 [00:01<00:00,  3.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  2.66it/s]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      33/50      2.06G      3.713      3.869      3.233         24        640: 100%|██████████| 4/4 [00:01<00:00,  2.33it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.09s/it]

                   all         51        180          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      34/50      2.06G      3.638      3.585      3.189         29        640: 100%|██████████| 4/4 [00:01<00:00,  3.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  2.19it/s]

                   all         51        180    5.3e-05     0.0026   0.000326   9.78e-05



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      35/50      2.06G      3.605      3.848      3.256         30        640: 100%|██████████| 4/4 [00:01<00:00,  3.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.67it/s]

                   all         51        180   0.000159    0.00779   0.000353   7.03e-05



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      36/50      2.06G      2.838      8.976      2.354          0        640: 100%|██████████| 4/4 [00:01<00:00,  2.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.72it/s]

                   all         51        180   0.000567     0.0291    0.00171   0.000255



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      37/50      2.06G      3.562      3.594      3.101         21        640: 100%|██████████| 4/4 [00:01<00:00,  2.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         51        180   0.000972     0.0527    0.00273   0.000543



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      38/50      2.06G      3.469      3.744       3.07         23        640: 100%|██████████| 4/4 [00:01<00:00,  2.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.68it/s]

                   all         51        180     0.0012     0.0686      0.004   0.000868



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      39/50      2.06G      3.781      4.571      3.174          9        640: 100%|██████████| 4/4 [00:01<00:00,  3.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.69it/s]

                   all         51        180    0.00128     0.0764    0.00623    0.00142



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      40/50      2.06G      3.479      3.555      3.052         28        640: 100%|██████████| 4/4 [00:01<00:00,  3.16it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.89it/s]

                   all         51        180    0.00129     0.0816     0.0115    0.00236


Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      41/50      2.06G      3.786      5.327      3.086          3        640: 100%|██████████| 4/4 [00:07<00:00,  1.77s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  2.34it/s]

                   all         51        180      0.827     0.0286     0.0147    0.00333



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      42/50      2.06G      3.684       4.69      3.114         18        640: 100%|██████████| 4/4 [00:01<00:00,  3.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  2.83it/s]

                   all         51        180      0.842     0.0156     0.0165    0.00411



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      43/50      2.06G      3.432      4.288      3.136          9        640: 100%|██████████| 4/4 [00:01<00:00,  3.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  3.17it/s]

                   all         51        180      0.875     0.0208     0.0193    0.00469



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      44/50      2.06G      3.462      5.964      3.116          3        640: 100%|██████████| 4/4 [00:01<00:00,  3.16it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.19it/s]

                   all         51        180      0.886     0.0234     0.0229    0.00568



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      45/50      2.06G       3.27      3.983      2.981          8        640: 100%|██████████| 4/4 [00:01<00:00,  2.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.57it/s]


                   all         51        180      0.851     0.0237     0.0251    0.00667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      46/50      2.06G      3.546      4.362      2.977         14        640: 100%|██████████| 4/4 [00:01<00:00,  3.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.88it/s]

                   all         51        180      0.854      0.039     0.0293    0.00721



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      47/50      2.06G      3.328      4.094      2.878         11        640: 100%|██████████| 4/4 [00:01<00:00,  3.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.52it/s]


                   all         51        180      0.835     0.0338     0.0324    0.00763

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      48/50      2.06G      3.511      4.737      3.059          5        640: 100%|██████████| 4/4 [00:01<00:00,  3.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.59it/s]

                   all         51        180      0.857     0.0312     0.0308    0.00779



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      49/50      2.06G      3.483      4.366       3.07          8        640: 100%|██████████| 4/4 [00:02<00:00,  1.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  2.52it/s]

                   all         51        180      0.858     0.0312     0.0289    0.00743



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      50/50      2.06G      3.262      4.241      2.936          5        640: 100%|██████████| 4/4 [00:01<00:00,  2.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.64it/s]

                   all         51        180      0.853     0.0338     0.0296    0.00752



50 epochs completed in 0.049 hours.
Optimizer stripped from runs/detect/train8/weights/last.pt, 6.3MB
Optimizer stripped from runs/detect/train8/weights/best.pt, 6.3MB

Validating runs/detect/train8/weights/best.pt...
Ultralytics 8.3.169 🚀 Python-3.11.13 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15095MiB)
YOLOv8n summary (fused): 72 layers, 3,006,623 parameters, 0 gradients


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.79it/s]


                   all         51        180      0.838     0.0364     0.0337    0.00782
                 Heads         22         70          1          0     0.0248     0.0063
                Person         26         77      0.188      0.182      0.144     0.0328
              Slippers          9         11          1          0          0          0
     Fire_extinguisher         11         11          1          0          0          0
      Protective_Shoes          9         11          1          0          0          0
Speed: 0.4ms preprocess, 2.9ms inference, 0.0ms loss, 6.1ms postprocess per image
Results saved to runs/detect/train8


In [ ]:
# !cp -r /content/dataset_enhanced /content/drive/MyDrive/VideoUpScaling/dataset_enhanced

In [ ]:
# !pip freeze > requirements.txt

In [ ]:

# !cp requirements.txt /content/drive/MyDrive/VideoUpScaling

In [114]:
from ultralytics import YOLO
model=YOLO("/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/runs/detect/train8/weights/best.pt")

In [ ]:
# import os

# img_dir = '/content/drive/MyDrive/VideoUpScaling/dataset/images/train'  # thư mục chứa ảnh
# label_dir = '/content/drive/MyDrive/VideoUpScaling/dataset/label2'  # thư mục chứa nhãn (YOLO .txt)

# os.makedirs(label_dir, exist_ok=True)

# # Lấy danh sách các file ảnh và sắp xếp
# image_files = sorted([f for f in os.listdir(img_dir) if f.endswith(('.jpg', '.png'))])

# # Tìm vị trí của file ảnh đích
# try:
#     stop_index = image_files.index('frame_00285_tile_1_2.png') + 1
# except ValueError:
#     print("Không tìm thấy file frame_00285_tile_1_2.png")
#     stop_index = len(image_files)


# for fname in image_files[:stop_index]:
#     name = os.path.splitext(fname)[0]
#     txt_path = os.path.join(label_dir, name + '.txt')
#     if not os.path.exists(txt_path):
#         open(txt_path, 'w').close()  # tạo file rỗng
#         print(f"Đã tạo file trống cho: {name}")

In [ ]:
# import sys
# sys.path.append('/content/drive/MyDrive')

# from VideoUpScaling.TilesDivision import TilesProcessor

# # === Mở comment code vẽ bounding box trong TilesDivision.py ===
# with open('/content/drive/MyDrive/VideoUpScaling/TilesDivision.py', 'r') as f:
#     lines = f.readlines()

# with open('/content/drive/MyDrive/VideoUpScaling/TilesDivision.py', 'w') as f:
#     for line in lines:
#         if '# cv2.rectangle' in line or '# cv2.putText' in line:
#             f.write(line.replace('# ', ''))
#         else:
#             f.write(line)

# # === Gọi processor ===
# tile_processor = TilesProcessor(
#     resize_size=(960, 960),
#     mode="test",  # hoặc "train"
#     output_dir="/content/drive/MyDrive/VideoUpScaling/InferenceTest"
# )

# # === Gọi xử lý ===
# # Nếu bạn muốn chạy 1 ảnh duy nhất:
# results = tile_processor.TilesDivision(
#     input="/content/drive/MyDrive/VideoUpScaling/test.png",  # ảnh đầu vào
#     model=model
# )

In [99]:
import cv2
import os

def draw_yolo_labels(image, label_path, class_names=None, box_color=(0, 255, 0)):
    h, w, _ = image.shape

    if not os.path.exists(label_path):
        print(f"Label file not found: {label_path}")
        return image

    with open(label_path, 'r') as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) != 5:
                continue

            cls_id, x_center, y_center, bw, bh = map(float, parts)
            cls_id = int(cls_id)

            # Convert relative to absolute pixel coordinates
            x_center *= w
            y_center *= h
            bw *= w
            bh *= h

            x1 = int(x_center - bw / 2)
            y1 = int(y_center - bh / 2)
            x2 = int(x_center + bw / 2)
            y2 = int(y_center + bh / 2)

            label = f"{class_names[cls_id]}" if class_names and cls_id < len(class_names) else f"Class {cls_id}"

            # Draw box and label
            cv2.rectangle(image, (x1, y1), (x2, y2), box_color, 2)
            cv2.putText(image, label, (x1, max(y1 - 10, 0)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, box_color, 2)

    return image


In [ ]:
class_names=["Heads","Person","Slippers","Fire_extinguisher","Protective_Shoes"]

In [115]:
# Gán tên ảnh gốc và đường dẫn nhãn tương ứng
image_name = os.path.basename(input_image_path).replace('.png', '')  # ví dụ: "test"
label_file = f"{image_name}.txt"  # ví dụ: test.txt
label_dir = "/content/drive/MyDrive/VideoUpScaling/labels/"  # thư mục chứa nhãn
label_path = os.path.join(label_dir, label_file)

# Vẽ box từ nhãn
tile = draw_yolo_labels(tile, label_path, model.names)

Label file not found: /content/drive/MyDrive/VideoUpScaling/labels/test.txt


In [116]:
import cv2
import os
from ultralytics import YOLO

# Define input image path and output directory
input_image_path = "/content/drive/MyDrive/VideoUpScaling/test.png"
output_dir = "/content/drive/MyDrive/VideoUpScaling/InferenceTest_explicit_draw" # New output directory
os.makedirs(output_dir, exist_ok=True)

# Load the image
image = cv2.imread(input_image_path)
if image is None:
    print(f"Error: Could not load image from {input_image_path}")
else:
    h, w, _ = image.shape

    # Define tile size (dividing into 3x3 grid)
    tile_h = h // 3
    tile_w = w // 3

    # Load the YOLO model (assuming it's already loaded in a previous cell)
    # model = YOLO("/content/drive/.shortcut-targets-by-id/1ivzWHCgPHrXYfA0oEV3Moo7u1XCvqRM8/VideoUpScaling/dataset_enhanced/runs/detect/train5/weights/best.pt")

    # Define class names (assuming they are defined in a previous cell)
    # class_names=["Heads","Person","Slippers","Fire_extinguisher","Protective_Shoes"]


    # Process each tile
    for i in range(3):
        for j in range(3):
            # Calculate tile coordinates
            y_start = i * tile_h
            y_end = (i + 1) * tile_h
            x_start = j * tile_w
            x_end = (j + 1) * tile_w

            # Extract the tile
            tile = image[y_start:y_end, x_start:x_end].copy() # Use .copy() to avoid modifying the original image slice

            # Perform inference on the tile
            results = model(tile)[0]

            # Get bounding box information in YOLO format (relative coordinates)
            yolo_labels = []
            for r in results.boxes:
                cls = int(r.cls[0])
                # Convert absolute xyxy to relative xywh for the tile
                x_center_abs, y_center_abs, width_abs, height_abs = r.xywh[0].cpu().numpy()
                # Calculate relative coordinates within the tile
                x_center_rel = x_center_abs / tile.shape[1]
                y_center_rel = y_center_abs / tile.shape[0]
                width_rel = width_abs / tile.shape[1]
                height_rel = height_abs / tile.shape[0]

                yolo_labels.append(f"{cls} {x_center_rel:.6f} {y_center_rel:.6f} {width_rel:.6f}")

            # Create a dummy label file path for the draw_yolo_labels function
            # We will pass the labels directly, so the file doesn't need to exist
            dummy_label_path = "dummy_label.txt"

            # Draw bounding boxes and labels on the tile using the imported function
            # We need to adapt draw_yolo_labels to take labels directly or write to a temp file
            # For simplicity, let's write to a temporary file and then read it
            temp_label_file = os.path.join(output_dir, f"temp_tile_{i}_{j}.txt")
            with open(temp_label_file, 'w') as f:
                for label_line in yolo_labels:
                    f.write(label_line + '\n')

            # Draw boxes from the temporary label file
            annotated_tile = draw_yolo_labels(tile, temp_label_file, class_names=model.names) # Pass model.names for class names

            # Remove the temporary label file
            os.remove(temp_label_file)


            # Save the annotated tile
            output_tile_path = os.path.join(output_dir, f"tile_{i}_{j}.png")
            cv2.imwrite(output_tile_path, annotated_tile)
            print(f"Saved annotated tile: {output_tile_path}")


0: 320x640 (no detections), 12.0ms
Speed: 1.8ms preprocess, 12.0ms inference, 0.7ms postprocess per image at shape (1, 3, 320, 640)
Saved annotated tile: /content/drive/MyDrive/VideoUpScaling/InferenceTest_explicit_draw/tile_0_0.png

0: 320x640 (no detections), 8.1ms
Speed: 2.2ms preprocess, 8.1ms inference, 0.7ms postprocess per image at shape (1, 3, 320, 640)
Saved annotated tile: /content/drive/MyDrive/VideoUpScaling/InferenceTest_explicit_draw/tile_0_1.png

0: 320x640 (no detections), 7.8ms
Speed: 1.8ms preprocess, 7.8ms inference, 0.6ms postprocess per image at shape (1, 3, 320, 640)
Saved annotated tile: /content/drive/MyDrive/VideoUpScaling/InferenceTest_explicit_draw/tile_0_2.png

0: 320x640 (no detections), 9.9ms
Speed: 2.2ms preprocess, 9.9ms inference, 0.7ms postprocess per image at shape (1, 3, 320, 640)
Saved annotated tile: /content/drive/MyDrive/VideoUpScaling/InferenceTest_explicit_draw/tile_1_0.png

0: 320x640 (no detections), 7.7ms
Speed: 1.9ms preprocess, 7.7ms infe

In [117]:
import cv2
from ultralytics import YOLO

# Chạy bình thường, đưa cả video vào

# Input video
video_path = '/content/drive/MyDrive/VideoUpScaling/10.72.216.20_.mp4'
cap = cv2.VideoCapture(video_path)

# Lấy thông tin video
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)

# Ghi video đầu ra
output_path = 'output_video.mp4'
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

# Xử lý từng frame
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Inference
    results = model(frame)[0]

    # Vẽ bounding boxes
    for box in results.boxes:
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        cls = int(box.cls[0])
        conf = float(box.conf[0])
        class_name = model.names[cls]

        label = f"{class_name} {conf:.2f}"
        color = (0, 255, 0)
        cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
        cv2.putText(frame, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

    # Ghi vào video output
    out.write(frame)

# Giải phóng tài nguyên
cap.release()
out.release()
cv2.destroyAllWindows()


Streaming output truncated to the last 5000 lines.
0: 320x640 (no detections), 12.0ms
Speed: 3.9ms preprocess, 12.0ms inference, 0.7ms postprocess per image at shape (1, 3, 320, 640)

0: 320x640 (no detections), 11.0ms
Speed: 3.2ms preprocess, 11.0ms inference, 0.7ms postprocess per image at shape (1, 3, 320, 640)

0: 320x640 (no detections), 10.4ms
Speed: 7.0ms preprocess, 10.4ms inference, 0.7ms postprocess per image at shape (1, 3, 320, 640)

0: 320x640 (no detections), 12.4ms
Speed: 3.1ms preprocess, 12.4ms inference, 1.3ms postprocess per image at shape (1, 3, 320, 640)

0: 320x640 (no detections), 8.9ms
Speed: 3.3ms preprocess, 8.9ms inference, 0.7ms postprocess per image at shape (1, 3, 320, 640)

0: 320x640 (no detections), 9.1ms
Speed: 3.8ms preprocess, 9.1ms inference, 0.7ms postprocess per image at shape (1, 3, 320, 640)

0: 320x640 (no detections), 10.0ms
Speed: 3.3ms preprocess, 10.0ms inference, 0.7ms postprocess per image at shape (1, 3, 320, 640)

0: 320x640 (no detecti

In [118]:
import cv2
import numpy as np
from ultralytics import YOLO

#chia 9 tile => upscale => inference

# Optional: Super resolution model (ví dụ: ESRGAN, RealESRGAN, BSRGAN)
def enhance_tile(tile):
      model = BSRGANModule.BSRGAN(model_names=["BSRGAN"],scale_factor=4)
  # Process each image and its corresponding label file

      # # Enhance the image
      # img_L = util.imread_uint(image_path, n_channels=3)
      # img_L = util.uint2tensor4(img_L)
      # img_L = img_L.to('cuda' if torch.cuda.is_available() else 'cpu')

      # with torch.no_grad():
      #     img_E = model.netG(img_L)

      # img_E = util.tensor2uint(img_E)
      # output_image_path = os.path.join(output_image_dir, image_name)
      # util.imsave(img_E, output_image_path)
      tile=model.Enhance(input=image_path)
      # # Scale and save the new labels
      # if os.path.exists(input_label_dir):
      #     with open(input_label_dir, 'r') as f_in, open(os.path.join(output_label_dir, os.path.splitext(image_name)[0] + '.txt'), 'w') as f_out:
      #         for line in f_in:
      #             parts = line.strip().split()
      #             cls = int(parts[0])
      #             x_center, y_center, width, height = map(float, parts[1:])

      #             # Bounding box coordinates are relative to image size, so no change is needed.
      #             f_out.write(f"{cls} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}\n")
      return tile  # hoặc tile_upscaled = sr_model.enhance(tile)

# Input/output video
cap = cv2.VideoCapture('/content/drive/MyDrive/VideoUpScaling/10.72.216.20_.mp4')
fps = cap.get(cv2.CAP_PROP_FPS)
w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
out = cv2.VideoWriter('output2.mp4', cv2.VideoWriter_fourcc(*'mp4v'), fps, (w, h))

# Chia tile
tile_h = h // 3
tile_w = w // 3

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    combined_boxes = []

    # Chia frame thành 3x3 và xử lý từng tile
    for i in range(3):
        for j in range(3):
            y0, y1 = i * tile_h, (i + 1) * tile_h
            x0, x1 = j * tile_w, (j + 1) * tile_w
            tile = frame[y0:y1, x0:x1].copy()

            # Step 2: SR (tăng chất lượng)
            tile = enhance_tile(tile)

            # Step 3: YOLO inference trên tile
            results = model(tile)[0]

            for box in results.boxes:
                x1_box, y1_box, x2_box, y2_box = box.xyxy[0]
                cls = int(box.cls[0])
                conf = float(box.conf[0])

                # Dịch tọa độ về frame gốc
                x1_full = int(x1_box + x0)
                y1_full = int(y1_box + y0)
                x2_full = int(x2_box + x0)
                y2_full = int(y2_box + y0)

                combined_boxes.append((x1_full, y1_full, x2_full, y2_full, cls, conf))

    # Step 5: Vẽ bounding box lên frame gốc
    for x1, y1, x2, y2, cls, conf in combined_boxes:
        label = f"{model.names[cls]} {conf:.2f}"
        color = (0, 255, 0)
        cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
        cv2.putText(frame, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

    out.write(frame)

cap.release()
out.release()
cv2.destroyAllWindows()


Streaming output truncated to the last 5000 lines.

0: 640x640 (no detections), 8.1ms
Speed: 17.3ms preprocess, 8.1ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 640)
LogHandlers exist!
[3, 3, 64, 23, 32, 4]

0: 640x640 (no detections), 8.9ms
Speed: 17.9ms preprocess, 8.9ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 640)
LogHandlers exist!
[3, 3, 64, 23, 32, 4]

0: 640x640 (no detections), 8.4ms
Speed: 18.4ms preprocess, 8.4ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 640)
LogHandlers exist!
[3, 3, 64, 23, 32, 4]

0: 640x640 (no detections), 9.5ms
Speed: 22.0ms preprocess, 9.5ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 640)
LogHandlers exist!
[3, 3, 64, 23, 32, 4]

0: 640x640 (no detections), 8.1ms
Speed: 19.2ms preprocess, 8.1ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 640)
LogHandlers exist!
[3, 3, 64, 23, 32, 4]

0: 640x640 (no detections), 9.5ms
Speed: 18.5ms preprocess, 9.5ms inference, 0.8ms 

KeyboardInterrupt: 